version: '3.7'
services:
  nodejs-service:
    image: abeesdevjs/file-string-be:latest
    deploy:
      mode: global
    ports:
      - '8080:8080'
    environment:
      - CONFIG_PORT=8080
      - CONFIG_PREFIX=/api/v1
      - CONFIG_DB_HOST=52.221.192.74
      - CONFIG_DB_PORT=5432
      - CONFIG_DB_USER=postgres
      - CONFIG_DB_PASS=rB5aRD4sQIWt3YM7IvmwCBJDgoyKfC6b
      - CONFIG_DB_NAME=filestring
      - CONFIG_ACCESS_TOKEN_SECRET=access-token-secret
      - CONFIG_REFRESH_TOKEN_SECRET=refresh-token-secret
      - CONFIG_REDIS_URL=redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@54.169.213.226:6379
      - CONFIG_REDIS_PORT=6379
      - CONFIG_REDIS_HOST=54.169.213.226
      - CONFIG_REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - CONFIG_REDIS_DB=0
      - CONFIG_FRONTEND_URL=https://filestring.abeesdev.com
