name: nestjs-service
on:
  push:
    branches:
      - main
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout/@v2
      - name: action/setup-node
        run: cd ./back-end && chmod +x ./deploy.sh && ./deploy.sh
        shell: bash
      - name: action/login-hub
        uses: docker/login-action@v1
        with:
          username: abeesdevjs
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: action/setup-buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: action/docker-buildx-action
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./back-end/docker
          file: ./back-end/docker/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: 'abeesdevjs/file-string-be:latest'
  deploy-fontend:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout/@v2
      - name: action/setup-node
        run: cd ./front-end && chmod +x ./deploy.sh && ./deploy.sh
        shell: bash
      - name: action/login-hub
        uses: docker/login-action@v1
        with:
          username: abeesdevjs
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: action/setup-buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: action/docker-buildx-action
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./front-end/docker
          file: ./front-end/docker/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: 'abeesdevjs/file-string-fe:latest'

